name: Auto Lint and Commit with Gradle

on:
  push:
    branches:
      - main

jobs:
  lint-and-commit:
    name: Lint and Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Gradle Lint
        run: ./gradlew lint

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --exit-code
          echo "has_changes=$(test $? -ne 0 && echo true || echo false)" >> $GITHUB_ENV

      - name: Commit Changes
        if: env.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto lint fixes"
          git push
